export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT='REMOVE_ALERT'


//POKEMON
export const GET_POKEMON = 'GET_POKEMON'
export const SHOW_POKEMON = 'SHOW_POKEMON'
export const FETCH_ERROR = 'FETCH_ERROR'

//Favorite Pokemon

export const ADD_FAVORITE= 'ADD_FAVORITE'
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE'

export const GET_TYPE = 'GET_TYPE'



export const SET_TEXT_FILTER = 'SET_TEXT_FILTER'
export const SET_GENDER_FILTER = 'SET_GENDER_FILTER'
export const SET_HABITAT_FILTER= 'SET_HABITAT_FILTER'
export const SET_REGION_FILTER= 'SET_REGION_FILTER'







